# Generated by Django 5.0.6 on 2024-05-21 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_gallery'),
    ]

    operations = [
        migrations.AddField(
            model_name='gallery',
            name='status',
            field=models.CharField(choices=[('publish', 'publish'), ('unpublish', 'unpublish')], default='unpublish', max_length=200),
        ),
    ]
