# Generated by Django 5.0.6 on 2024-05-25 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0006_alter_news_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='gallery',
            name='category',
            field=models.CharField(choices=[('cartoon', 'cartoon'), ('movie', 'movie'), ('sports', 'sports')], default='movie', max_length=200),
        ),
    ]
